import type { Metadata } from 'next'
import { Inter, Cairo, Open_Sans, Noto_Sans_Javanese } from 'next/font/google'

import localFont from 'next/font/local';
import './globals.css'

import { ThemeProvider } from '@/components/providers/ThemeProvider'
import { Header } from '@/components/ui/shared/Header'
import { Footer } from '@/components/ui/shared/Footer'



const inter = Inter({ subsets: ['latin'] })
const opens_sans = Open_Sans({ subsets: ['latin'] })


// Local Fonts
const caros = localFont({
  src: [
    {
      path: './fonts/caros/cretype-Caros-Light.woff',
      weight: '100',
      style: 'normal',
    },
    {
      path: './fonts/caros/cretype-Caros.woff',
      weight: '200',
      style: 'normal',
    },
    {
      path: './fonts/caros/cretype-Caros-Medium.woff',
      weight: '300',
      style: 'normal',
    },
    /*{
      path: './fonts/caros/RNSSanz-SemiBold.otf',
      weight: '400',
      style: 'normal',
    },*/
    {
      path: './fonts/caros/cretype-Caros-Bold.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/caros/cretype-Caros-ExtraBold.woff',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/caros/cretype-Caros-Black.woff',
      weight: '700',
      style: 'normal',
    },
  ]
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" /*className='sm:scroll-smooth'*/>
      <body className={`min-h-screen bg-[#f5f5f5] dark:bg-[#121212] dark:text-white ${inter.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <main className=''>
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
